### ISSUE TITLE
src/ob/string.hh:7:20 not found

### ISSUE THREAD

**Issue by elhenro** [octobanana/fltrdr#1]
Hey, I liked to try out your project but i'm getting the following error while trying to build or install:

`[...]/fltrdr/./src/ob/string.hh:7:20: fatal error: optional: No such file or directory
compilation terminated.
CMakeFiles/fltrdr.dir/build.make:62: recipe for target 'CMakeFiles/fltrdr.dir/src/main.cc.o' failed
make[2]: *** [CMakeFiles/fltrdr.dir/src/main.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/fltrdr.dir/all' failed
make[1]: *** [CMakeFiles/fltrdr.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
i install your parg lib, libstdc++6 and have cmake 3.14
ubuntu 16.04..

(Edit: same for peaclock)

**Comment by octobanana** [comment]
It looks like the error is due to the compiler not supporting `std::optional`, a C++17 feature. What compiler/version are you using?

**Comment by elhenro** [comment]
thanks @octobanana, that must be the issue. will reopen an issue if i cant fix.
edit: i am using your recommended versions.

**Comment by elhenro** [comment]
cant manage to get ` libstdc++6`  - `GLIBCXX_3.4.22` installed, so far. also  tried using the  `ppa:ubuntu-toolchain-r/test` repo..
This problem is unrelated but if you'd have tips i'd be grateful. 
any chance i can compile with an older version?

**Comment by octobanana** [comment]
Can you install gcc version 8 from a ppa?

**Comment by octobanana** [comment]
Feel free to reopen, or create a new issue if you need any help.
