### ISSUE TITLE
Fedora 31: Build error

### ISSUE THREAD

**Issue by winderickxeli** [octobanana/fltrdr#14]
Hi

I'm here once again to ask your assistance! I really like this project and would like to use this on fedora. I **think** I installed all the necessary packages.
- icu
- gcc
- cmake
Relevant errors
-----------------

````
-- Build files have been written to: /home/ew/Documents/Proj/fltrdr/build/release
[ 14%] Building CXX object CMakeFiles/fltrdr.dir/src/main.cc.o
In file included from /home/ew/Documents/Proj/fltrdr/./src/fltrdr/fltrdr.hh:5,
                 from /home/ew/Documents/Proj/fltrdr/src/fltrdr/tui.hh:4,
                 from /home/ew/Documents/Proj/fltrdr/src/main.cc:7:
/home/ew/Documents/Proj/fltrdr/./src/ob/text.hh:6:10: fatal error: unicode/coll.h: No such file or directory
    6 | #include <unicode/coll.h>
      |          ^~~~~~~~~~~~~~~~
````

**Comment by octobanana** [comment]
I think you may need two additional packages:
* __libicu__
* __libicu-devel__

Let me know how it goes!

**Comment by winderickxeli** [comment]
Thanks! I also seemed to need **openssl-devel**. After that, it worked like a charm!
