### ISSUE TITLE
Clarify Text Styles

### ISSUE THREAD

**Issue by pigmonkey** [octobanana/fltrdr#6]
Looking at the output of `--help`, it is difficult to discern what the various text style values (`text`, `text-primary`, `text-secondary`, `text-highlight`, etc) refer to.

When I first launched fltrdr on a text file I found the behaviour of highlighting the character under the cursor to be distracting. I wanted to highlight the whole word. Through trial and error I discovered that the property I wanted was `text-primary`, but it would have been helpful if the documentation was more specific on this point.

**Comment by octobanana** [comment]
Thanks for letting me know, I'll try and make the descriptions of each style more specific.

**Comment by octobanana** [comment]
Some more specific descriptions have been added in the latest version. Could you let me know if they help clarify the commands purpose? If not, what could be changed?

**Comment by pigmonkey** [comment]
Yes, these look much more helpful. Thanks!
