### ISSUE TITLE
warning: unknown command 'style text-brace 4feae7'

### ISSUE THREAD

**Issue by pigmonkey** [octobanana/fltrdr#7]
Using the [example config](https://github.com/octobanana/fltrdr/blob/master/example/config) with fltrdr v0.1.0 (18.02.2019) currently results in the warning: `unknown command 'style text-brace 4feae7'`.

**Comment by octobanana** [comment]
Ah, I must have left that in while testing, It's not a valid command. I'll remove it, thanks for letting me know!

**Comment by octobanana** [comment]
Fixed in commit 0e7c98cc1f81d18cc577a2ac6d036ffb5422eb14.

Thanks again!
