### ISSUE TITLE
Error: could not open stdin with docker

### ISSUE THREAD

**Issue by foobert** [octobanana/fltrdr#9]
I'm trying to build this into a Docker image but can't get stdin to work. It's very likely that I'm missing something Docker specific, but I'm not sure.

The error I get is: `Error: could not open stdin` using the following Dockerfile

```FROM alpine AS build
RUN apk add --no-cache bash cmake make g++
WORKDIR /app
COPY CMakeLists.txt build.sh env.sh /app/
COPY src /app/src/
RUN ./build.sh

FROM alpine
RUN apk add --no-cache libstdc++
COPY --from=build /app/build/release/fltrdr /usr/bin/
ENTRYPOINT ["/usr/bin/fltrdr"]

**Comment by octobanana** [comment]
The error being thrown is due to the file `/dev/tty` being unable to be opened. 

I'm not very familiar with Docker. Is it running in an interactive/tty environment? What's the docker command used to run it look like, such as `docker exec ...`?

**Comment by foobert** [comment]
Hmm, still can't get it to work, but since macos build is fixed, I'll close this issue.
